--- 
title: "NYC Yellow Taxi Tipping Patterns"
author: "Vivian Liu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

## Data
In this project, I intend to use the 2021 Yellow Taxi Trip Data. I got the data from NYC's OpenData source, linked here: https://data.cityofnewyork.us/Transportation/2021-Yellow-Taxi-Trip-Data/m6nq-qud6.

I want to use the tip information, given as a "tip amount" column, and divide it by the "fare amount" column in order to create a tip rate. I plan to use the other predictors in the data (such as time of ride, passenger count, etc) to predict whether or not a given rider (or riders) tipped over 15% on their ride. 


## Modeling Goal 
I’d like to use different column values (borough, time of day, weekend vs not weekend, payment type) to predict whether or not the rider gives the driver a tip. Since tip amount is a continuous variable, instead I could categorize this variable as more or less than 15% tip (compared with the fare amount).  


## Models
I intend to use the following models:

* OneR
* Decision Tree
* Random Forest
* Naive Bayes

For each of these models, I will create visualizations to interpret my results, and ultimately produce accuracies and sensitivy/specifity values so as to be able to compare the models against each other in terms of prediction efficacy. 


## Data Sources

https://catalog.data.gov/dataset/nyc-taxi-zones
https://www.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf
https://catalog.data.gov/dataset/nyc-taxi-zones




